config/routes.rb
Cataroca::Application.routes.draw do
  resources :sprints

  resources :projetos

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base

  before_update :validar, :validar_atualizar
  before_create :validar, :validar_criar

  has_many :sprints

  def validar

    if self.nome.blank?
      self.errors.add(:nome, I18n.t('.projeto.nome.invalido'))
    end

    self.errors.empty?

  end

  def validar_criar

    unless Projeto.where("nome = :nome and ativo = 1", {:nome => self.nome}).empty?
      self.errors.add(:nome, I18n.t('.projeto.nome.unico'))
    end

    self.errors.empty?

  end

  def validar_atualizar

    unless Projeto.where("nome = :nome and id != :id and ativo = 1", {:nome => self.nome, :id => self.id}).empty?
      self.errors.add(:nome, I18n.t('.projeto.nome.unico'))
    end

    self.errors.empty?

  end

  def destroy
    self.update_column(:ativo, 0)
  end

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base

  before_update :validar, :validar_atualizar
  before_create :validar, :validar_criar

  belongs_to :projeto

  def validar

    if self.nome.blank?
      self.errors.add(:nome, I18n.t('.sprint.nome.invalido'))
    end

    if self.inicio.blank?
      self.errors.add(:inicio, I18n.t('.sprint.inicio.invalido'))
    end

    if self.fim.blank?
      self.errors.add(:fim, I18n.t('.sprint.fim.invalido'))
    end

    if !self.fim.blank? and !self.fim.blank? and self.fim < self.inicio
      self.errors.add(:fim, I18n.t('.sprint.fim.menor'))
    end

    if self.projeto.blank?
      self.errors.add(:projeto, I18n.t('.projeto.projeto.invalido'))
    end

    self.errors.empty?

  end

  def validar_criar



    self.errors.empty?

  end

  def validar_atualizar



    self.errors.empty?

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController

  def index
    @projetos = Projeto.all
  end

  def show
    @projeto = Projeto.find(params[:id])
  end

  def new
    @projeto = Projeto.new
  end

  def edit
    @projeto = Projeto.find(params[:id])
  end

  def create
    @projeto = Projeto.new(params[:projeto])

    if @projeto.save
      redirect_to @projeto, :notice => I18n.t('.projeto.criado')
    else
      render :action => "new"
    end
  end

  def update
    @projeto = Projeto.find(params[:id])

    if @projeto.update_attributes(params[:projeto])
      redirect_to @projeto, :notice => I18n.t('.projeto.atualizado')
    else
      render :action => "edit"
    end
  end

  def destroy
    @projeto = Projeto.find(params[:id])
    @projeto.destroy

    redirect_to projetos_url
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController

  def index
    @sprints = Sprint.all
  end

  def show
    @sprint = Sprint.find(params[:id])
  end

  def new
    @sprint = Sprint.new
  end

  def edit
    @sprint = Sprint.find(params[:id])
  end

  def create
    @sprint = Sprint.new(params[:sprint])

    if @sprint.save
      redirect_to @sprint, :notice => 'Sprint was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @sprint = Sprint.find(params[:id])

    if @sprint.update_attributes(params[:sprint])
      redirect_to @sprint, :notice => 'Sprint was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @sprint = Sprint.find(params[:id])
    @sprint.destroy

    redirect_to sprints_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>teste</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editing projeto</h1>

<%= render 'form' %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

app/views/projetos/index.html.erb
<h1>Listing projetos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projetos.each do |projeto| %>
  <tr>
    <td><%= projeto.nome %></td>
    <td><%= link_to 'Show', projeto %></td>
    <td><%= link_to 'Edit', edit_projeto_path(projeto) %></td>
    <td><%= link_to 'Destroy', projeto, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Projeto', new_projeto_path %>

app/views/projetos/new.html.erb
<h1>New projeto</h1>

<%= render 'form' %>

<%= link_to 'Back', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @projeto.nome %>
</p>


<%= link_to 'Edit', edit_projeto_path(@projeto) %> |
<%= link_to 'Back', projetos_path %>

app/views/sprints/_form.html.erb
<%= form_for(@sprint) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br />
    <%= f.text_field :inicio %>
  </div>
  <div class="field">
    <%= f.label :fim %><br />
    <%= f.text_field :fim %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<h1>Editing sprint</h1>

<%= render 'form' %>

<%= link_to 'Show', @sprint %> |
<%= link_to 'Back', sprints_path %>

app/views/sprints/index.html.erb
<h1>Listing sprints</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Inicio</th>
    <th>Fim</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sprints.each do |sprint| %>
  <tr>
    <td><%= sprint.nome %></td>
    <td><%= sprint.descricao %></td>
    <td><%= sprint.inicio %></td>
    <td><%= sprint.fim %></td>
    <td><%= link_to 'Show', sprint %></td>
    <td><%= link_to 'Edit', edit_sprint_path(sprint) %></td>
    <td><%= link_to 'Destroy', sprint, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sprint', new_sprint_path %>

app/views/sprints/new.html.erb
<h1>New sprint</h1>

<%= render 'form' %>

<%= link_to 'Back', sprints_path %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @sprint.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @sprint.descricao %>
</p>

<p>
  <b>Inicio:</b>
  <%= @sprint.inicio %>
</p>

<p>
  <b>Fim:</b>
  <%= @sprint.fim %>
</p>


<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>